name: information_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
      
  design_system:
    path: ./design_system

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  uuid: ^4.1.0
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true